body_forge/accounts/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path, include

from body_forge.accounts import views

urlpatterns = [
    path('login/', views.AppUserLoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('register/', views.AppUserRegisterView.as_view(), name="register"),
    path('profile/<int:pk>/', include([
        path('', views.ProfileDetailsView.as_view(), name="details"),
        path('edit/', views.ProfileEditView.as_view(), name="edit"),
        path('delete/', views.ProfileDeleteView.as_view(), name="delete")
    ]))
]

body_forge/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

urlpatterns = ([
    path('admin/', admin.site.urls),
    path('', include("body_forge.common.urls")),
    path('accounts/', include("body_forge.accounts.urls")),
    path('workouts/', include("body_forge.workouts.urls")),
    path('exercises/', include("body_forge.exercises.urls")),
    path('muscle_groups/', include("body_forge.muscle_groups.urls")),
])

urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

body_forge/accounts/models/app_profile.py
from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator
from django.db import models


UserModel = get_user_model()

class Profile(models.Model):
    user = models.OneToOneField(
        to=UserModel,
        on_delete=models.CASCADE,
        primary_key=True,
    )
    username = models.CharField(
        max_length=30,
        blank=False,
        null=True,
    )
    first_name = models.CharField(
        max_length=30,
        blank=True,
        null=True,
    )
    last_name = models.CharField(
        max_length=30,
        blank=True,
        null=True,
    )
    height = models.DecimalField(
        max_digits=5,
        decimal_places=2,  # Supports 999.99cm
        blank=True,
        null=True,
        validators=[
            MinValueValidator(0.01),
        ]
    )
    body_weight = models.DecimalField(
        max_digits=6,
        decimal_places=2,  # Supports 9999.99kg
        blank=True,
        null=True,
        validators=[
            MinValueValidator(0.01)
        ]
    )
    date_of_birth = models.DateField(
        blank=True,
        null=True,
    )
    date_joined = models.DateField(
        auto_now_add=True,
        blank=True,
        null=True,
    )
    profile_picture = models.ImageField(
        upload_to='profile_pictures/',
        blank=True,
        null=True,
    )

    def __str__(self):
        return self.username or self.user.email

body_forge/accounts/models/app_user.py
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.db import models

from body_forge.accounts.managers import AppUserManager


class AppUser(AbstractBaseUser, PermissionsMixin):
    email =models.EmailField(unique=True)

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = AppUserManager()

body_forge/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from body_forge.accounts.models import Profile

UserModel = get_user_model()


class AppUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = UserModel


class AppUserCreationForm(UserCreationForm):
    class Meta:
        model = UserModel
        fields = ("email", "password1", "password2")

        widgets = {
            'email': forms.TextInput(attrs={"class": "form-control"}),
            'password1': forms.PasswordInput(attrs={"class": "form-control"}),
            'password2': forms.PasswordInput(attrs={"class": "form-control"}),
        }


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ("user", "date_joined", "date_of_birth")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['profile_picture'].widget = forms.FileInput(attrs={
            'accept': 'image/*'
        })

        self.fields['height'].help_text = "in centimeters"
        self.fields['body_weight'].help_text = "in kilograms"

body_forge/accounts/views.py
from django.contrib.auth import get_user_model, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.views import LoginView
from django.http import HttpResponseNotAllowed
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView

from body_forge.accounts.forms import AppUserCreationForm, ProfileEditForm
from body_forge.accounts.models import Profile

UserModel = get_user_model()


class AppUserLoginView(LoginView):
    template_name = "accounts/user-login-page.html"


class AppUserRegisterView(CreateView):
    model = UserModel
    form_class = AppUserCreationForm
    template_name = "accounts/user-register-page.html"
    success_url = reverse_lazy("home-page")

    def form_valid(self, form):
        response = super().form_valid(form)
        login(self.request, self.object)
        return response


class ProfileDetailsView(LoginRequiredMixin, DetailView):
    model = UserModel
    template_name = "accounts/profile-details-page.html"


class ProfileEditView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Profile
    form_class = ProfileEditForm
    template_name = "accounts/profile-edit-page.html"

    def test_func(self):
        profile = get_object_or_404(Profile, pk=self.kwargs['pk'])
        return self.request.user == profile.user

    def get_success_url(self):
        return reverse_lazy("details", kwargs={"pk": self.object.pk})


class ProfileDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Profile
    template_name = "accounts/profile-delete-page.html"
    success_url = reverse_lazy("home-page")

    def test_func(self):
        profile = get_object_or_404(Profile, pk=self.kwargs["pk"])
        return self.request.user == profile.user

    def post(self, request, *args, **kwargs):
        profile = self.get_object()
        user = profile.user
        logout(request)
        user.delete()
        return redirect(self.success_url)

templates/accounts/login-page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/accounts/profile-delete-page.html
{% extends 'common/base.html' %}
{% load static %}

{% block title %}Delete Profile{% endblock %}

{% block content %}
    <div class="delete-box-wrapper">
        <div class="delete-confirmation-box">
            <h2>Confirm Account Deletion</h2>
            <p class="warning-message">⚠️ Warning: This action cannot be undone!</p>
            <p>All your data will be permanently deleted.</p>

            <form method="post" action="{% url 'delete' pk=user.pk %}" class="choice-btn-box">
                {% csrf_token %}
                <button type="submit" class="yes-btn">Yes, Delete My Account</button>
                <a href="javascript:history.back()" class="no-btn">Cancel</a>
            </form>
        </div>
    </div>
{% endblock %}

templates/accounts/profile-details-page.html
{% extends 'common/base.html' %}
{% load static %}


{% block content %}
    <div class="profile-details-container">
        <div class="profile-card">
            <h1>Profile Details</h1>

            <div class="profile-image">
                {% if object.profile.profile_picture %}
                    <img src="{{ object.profile.profile_picture.url }}" alt="{{ object.username }}'s profile picture">
                {% else %}
                    <img src="{% static 'images/default-profile-pic/default-profile-image2.jpeg' %}" alt="">
                {% endif %}
            </div>

            <div class="profile-info">
                <div class="info-item">
                    <span class="label">Username:</span>
                    <span class="value">{{ object.profile.username|default:"empty" }}</span>
                </div>

                <div class="info-item">
                    <span class="label">First name:</span>
                    <span class="value">{{ object.profile.first_name|default:'empty' }}</span>
                </div>

                <div class="info-item">
                    <span class="label">Last name:</span>
                    <span class="value">{{ object.profile.last_name|default:'empty' }}</span>
                </div>

                <div class="body-info">
                    <div class="info-item">
                        <span class="label">Height:</span>
                        <span class="value">{{ object.profile.height }}</span>
                    </div>

                    <span class="border"></span>

                    <div class="info-item">
                        <span class="label">Weight:</span>
                        <span class="value">{{ object.profile.body_weight }}</span>
                    </div>
                </div>

                <div class="profile-actions">
                    <a href="{% url 'edit' pk=user.pk %}" class="profile-edit-btn">Edit Profile</a>
                    <a href="{% url 'home-page' %}" class="profile-details-back-btn">Back to Dashboard</a>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/accounts/profile-edit-page.html
{% extends 'common/base.html' %}
{% load static %}

{% block content %}
    <div class="profile-edit-container">
        <div class="profile-card">
            <h1>Profile Edit</h1>

            <form method="post" class="profile-edit-form-box" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="profile-image-container">

                    <div class="profile-image">
                        {% if object.profile_picture %}
                            <img id="profile-picture-preview" src="{{ object.profile_picture.url }}"
                                 alt="{{ object.username }}'s profile picture">
                        {% else %}
                            <img id="profile-picture-preview"
                                 src="{% static 'images/default-profile-pic/default-profile-image2.jpeg' %}"
                                 alt="{{ object.username }}'s profile picture">
                        {% endif %}
                    </div>
                    <label for="id_profile_picture" class="change-picture-btn">Change Profile Picture</label>
                    {{ form.profile_picture }}
                </div>

                {% for field in form %}
                    {% if field.name != 'profile_picture' %}
                        <p class="error">{{ field.errors }}</p>
                        <div class="label-input">
                            <label>{{ field.label }}</label>
                            {{ field }}
                        </div>
                        <br>
                    {% endif %}
                {% endfor %}

                <button class="profile-edit-save-btn" type="submit">Save</button>
            </form>
            <p>To delete the account <a href="{% url 'delete' pk=user.pk %}" class="delete-link">Click here</a></p>
        </div>
    </div>

    <script src="{% static 'js/accounts/profile-pic-change.js' %}"></script>
{% endblock %}

templates/accounts/user-login-page.html
{% extends 'common/base.html' %}
{% load placeholder_filter %}
{% load static %}

{% block title %}Login Page{% endblock %}

{% block content %}
    <div class="login-page-container">
        <div class="login-form-container">
            <form method="post" class="login-form">
                {% csrf_token %}
                <h1>Login</h1>

                <div class="field">
                    <h4 class="filed-title">Enter your Email:</h4>
                    {{ form.username|placeholder:"Email" }}
                    {{ form.username.errors }}
                </div>

                <div class="field">
                    <h4 class="filed-title">Enter your password:</h4>
                    {{ form.password|placeholder:"Password" }}
                    {{ form.password.errors }}
                </div>

                <button type="submit" class="login-btn">Login</button>

                <div class="second-option">
                    <p>Don't have an account? <a href="{% url 'register' %}" class="register-link">Click here</a></p>
                </div>

            </form>
        </div>
    </div>

{% endblock %}

templates/accounts/user-register-page.html
{% extends 'common/base.html' %}
{% load placeholder_filter %}
{% load static %}

{% block title %}Register User{% endblock %}

{% block content %}
    <div class="register-page-container">
        <div class="register-form-container">

            <form method="post" class="register-form">
                <h1>Register</h1>

                {% csrf_token %}

                <div class="field">
                    <h4 class="field-title">Email</h4>
                    {{ form.email|placeholder:"Email" }}
                    {{ form.email.errors }}
                </div>

                <div class="field">
                    <h4 class="field-title">Password:</h4>
                    {{ form.password1|placeholder:"Enter new password" }}
                    {{ form.password1.errors }}
                </div>

                <div class="field">
                    <h4 class="field-title">Confirm Password:</h4>
                    {{ form.password2|placeholder:"Confirm password" }}
                    {{ form.password2.errors }}
                </div>

                <button type="submit" class="register-form-btn">Submit</button>
            </form>

        </div>
    </div>
{% endblock %}